### ISSUE TITLE
Views customizing documentation broken link

### ISSUE THREAD

**Issue by paulocr** [Laravel-Backpack/Docs#100]
Hi,

The documentation to customize the blade views has a broken link.

In https://backpackforlaravel.com/docs/4.0/getting-started-basics the link to the "ridiculously easy." process to customize the views lead to a broken link: https://backpackforlaravel.com/docs/4.0/%7Bversion%7D#customize-views-for-each-crud-panel

Correct URL: https://backpackforlaravel.com/docs/4.0/crud-how-to#customize-views-for-each-crud-panel

**Comment by tabacitu** [comment]
Indeed! Thank you @paulocr , it's now fixed.
