### ISSUE TITLE
[Bug] Incorrectly shown code

### ISSUE THREAD

**Issue by genesiscz** [Laravel-Backpack/Docs#110]
Custom views code snippet in CRUD api page seems to be broken

![image](https://user-images.githubusercontent.com/1512353/76916075-a7b63580-68bf-11ea-8131-a2fe74f37ce0.png)

https://backpackforlaravel.com/docs/4.0/crud-api

I would create a PR, but is seems like a bug in the doc rather than in the doc file. 

It looks [perfectly fine](https://github.com/Laravel-Backpack/Docs/blob/master/4.0/crud-api.md)

**Comment by genesiscz** [comment]
While we're at this, it would probably be nice to 

1. show how to publish the base view that will be named "your-view" (I know it's shown else with buttons, but exactly for that reason I would include it there too. `php artisan backpack:publish crud/show`
2. where exactly this view needs to be resolved (probably good for newscomers into Laravel)

**Comment by tabacitu** [comment]
You're right! Thank you @genesiscz , fixed in https://github.com/Laravel-Backpack/Docs/commit/cb323600083b4aa0dda4f6ea1485cef5193cc154!
