### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by CreativeTransmissions** [Laravel-Backpack/Docs#111]
# Bug report

In the following document we are advised to set custom views per crud as follows:
$this->crud->setCreateView('your-view');
https://backpackforlaravel.com/docs/4.1/crud-how-to#customize-views-for-each-crud-panel

### What I did
Used the following:
$this->crud->setCreateView('my_create_view_name');

Folder location of view file:
resources/views/vendor/backpack/crud/my_create_view_name.blade.php

### What I expected to happen
The custom view would be used for one particular crud create view

### What happened
This gives a view not found error 

### What I've already tried to fix it
The solution is to use:
$this->crud->setCreateView('crud::my_create_view_name');

It would be useful if the documentation reflected this

**Comment by tabacitu** [comment]
You're right! Thank you @CreativeTransmissions & @genesiscz , fixed in https://github.com/Laravel-Backpack/Docs/commit/cb323600083b4aa0dda4f6ea1485cef5193cc154!

**Comment by genesiscz** [comment]
@tabacitu https://github.com/Laravel-Backpack/Docs/commit/cb323600083b4aa0dda4f6ea1485cef5193cc154#r37911692 ?
