### ISSUE TITLE
What about backpack/langfilemanager version for backpack/CRUD 4.0?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/docs#114]
I did find any place about `backpack/langfilemanager` version. When i update `backpack/CRUD 3.6 to 4.0`. I got backpack/langfilemanager `error. Previously i used `backpack/langfilemanager ^1.0`.

Can i remove `"backpack/base": "^1.0.0"` from `composer.json` ?

**Comment by tabacitu** [comment]
Yes definitely remove ```backpack/base``` from your composer.json - Backpack 4.x no longer uses it. Make sure you follow the [upgrade guide](https://backpackforlaravel.com/docs/4.0/upgrade-guide) closely.

Use version 2.* for LangFileManager - that one supports 4.1. Check out its github page for more information - https://github.com/Laravel-Backpack/LangFileManager . If you're upgrading to 4.1-beta I've also just pushed [4.1 support](https://github.com/Laravel-Backpack/LangFileManager/pull/79).

Cheers!
