### ISSUE TITLE
Page in docs is missing

### ISSUE THREAD

**Issue by shmuel-livshits** [Laravel-Backpack/docs#120]
https://backpackforlaravel.com/docs/4.0/crud-fluent-syntax#fluent-buttons-chained-methods

**Comment by tabacitu** [comment]
Indeed - that page only exists in 4.1 - because it's only a feature in 4.1. Check it out here - https://backpackforlaravel.com/docs/4.1/crud-fluent-syntax#fluent-buttons-chained-methods

@shmuel-livshits - how did you reach this page on the 4.0 docs?
