### ISSUE TITLE
What is the correct way to call store and update function?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/docs#121]
I looked backpack upgrade guide 3.6 to 4.0 and it shows `store and update` function have `$request` parameter like image 1
![1](https://user-images.githubusercontent.com/25341255/80897639-834fd480-8d18-11ea-8b51-8e535f378b52.png)
But after that i checked crud-operation-create and crud-operation-update function in doc it shows `store and update` function have not  `$request` parameter like image 2 and 3.
My question is which is the correct one?
![2](https://user-images.githubusercontent.com/25341255/80897640-85b22e80-8d18-11ea-933e-69a89884e074.png)
![3](https://user-images.githubusercontent.com/25341255/80897641-86e35b80-8d18-11ea-8e1d-d01cf13dfd59.png)

**Comment by tabacitu** [comment]
You don't _need_ to specify the request as a parameter. But you can if you want. Personally I prefer to not specify it, but I always _always_ make sure to run the validation inside ```setupCreateOperation()``` using ```$this->crud->setValidation(ArticleRequest::class);```

**Comment by senthu1994** [comment]
> You don't _need_ to specify the request as a parameter. But you can if you want.
> 
> Personally I prefer to not specify it, but I always _always_ make sure to manually run the validation inside `setupCreateOperation()` using `$this->crud->setValidation(ArticleRequest::class);`. This not only runs the validation, but also adds asterisks for the required inputs.

@tabacitu  Actually my question is about when i required to use `store or update` method. Because i have some work `before and after` doing `store or update` so that i am using `store or update` method.
From documentation information i am confused. So please check the question one more time and give the answer.
Thanks.

**Comment by tabacitu** [comment]
The correct one is without any parameters.

**Comment by senthu1994** [comment]
> The correct one is without any parameters.

@tabacitu Thanks. So please update in backpack 4 upgrade doc.
