### ISSUE TITLE
[4.1][Upgrade guide] - Add reference to the use of 'appends' in case of using an accessor

### ISSUE THREAD

**Issue by themagnifico** [Laravel-Backpack/docs#136]
Hi,
first of all thank you very much for all your efforts and your awesome product.

I have just upgraded Backpack from version 4.0 to 4.1.

The upgrade guide is very detailed, but i had a problem with an accessor column attribute.

After I investigated for a while I found out that i had to add the accessor attribute to the `$appends` model's variable.

As reported in this Pedro's comment (https://github.com/Laravel-Backpack/CRUD/pull/2732#issuecomment-624566624) i would suggest to add some reference  to the use of the following property:
```php
    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['snake_case_accessor'];

```
In my opinion the addition could be done in the **Model** section.

Since the use of the `$appends` is not requested by default using a model accessor (but just if the accessor computed values are to be added to the array / JSON representations of the model), 
it would be nice to have some reference also in the main guide.

Thanks
Luca

**Comment by tabacitu** [comment]
Thanks for reaching out @themagnifico ! Can you please help me better understand the issue?

So:
- you we upgrading from v4.0 to v4.1
- you had a `model_function` column (or maybe `model_function_attribute`)?
- after upgrading to v4.1, it didn't function as usual, you had to use `$appends` on the model?

I totally agree we should include `$appends` in the docs. I'm just wondering if it should be in the upgrade guide, or inside the docs for those column types.

What I don't understand is if it's something specific to 4.1 - that needs to be done differently there as opposed to 4.0. My tests show show everything's the same, but it wouldn't be the first time I'm wrong 😄 

Cheers!

**Comment by themagnifico** [comment]
Hi Crisitan,

version 4.0 was running smoothly.

After upgrading to version 4.1 a list view no longer worked.

The problem was due to a _select_ column with a custom accessor as attribute.

After upgrading to v4.1, the list view was empty returning the error _"Error loading page. Please, refresh the page."_ and in the network panel there was a 500 error  (_search_ via POST method).

The same problem is described in this issue/comment  https://github.com/Laravel-Backpack/CRUD/issues/2810#issuecomment-627324639

At the moment i think it should be included both in the upgrade guide and in the documentation (maybe in a particular section with reference to accessor with custom names).

Thanks 😄

**Comment by pxpm** [comment]
Hello guys!

Thanks for this PR @themagnifico but i think now it's not needed anymore. We decided to implement a solution that would not require users to add the mutated attribute to appends, so it will work as in 4.0. 

It's here the PR that implements it: https://github.com/Laravel-Backpack/CRUD/pull/2815

**Comment by tabacitu** [comment]
Pfiew! Thanks @pxpm & @themagnifico . Let's go with https://github.com/Laravel-Backpack/CRUD/pull/2815 - seems like an easier solution for the developer.
