### ISSUE TITLE
Possible miscommunication in 4.1 Upgrade Guide

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#192]
Here's what @azaricstefan had to say about it:

---

> Wanted to share these 2 things with you.
>  
> Step 9 useful updates:
> 1. I noticed that you didn’t take into account table revisions, I fixed that manually by just adding replace in the same migration that you created.
> 2. I had BackpackUser before, now I deleted it as per guide but I get errors such as:
>     - Call to undefined relationship [roles] on model [App\\Models\\User].
> Solution for this was to add this to User model:
> - `use Spatie\Permission\Traits\HasRoles;`
> - `use HasRoles;`
>  
> Maybe it will be useful to update the upgrade guide with these 2 points, if someone else is experiencing same issue as me.

---

Let's please investigate and see if we need to make changes to our guide or something.

**Comment by pxpm** [comment]
The first point is true indeed, We should also mention revisions table along with the poly permisisons table. If you have revisions you also need to replace the model string in database. Still true for any other case where you use `BackpackUser` model, it will need replace.

About the second issue, what I understand from it, is that you manually need to add the relations etc to the new User model (kind of instalation for PermissionManager package). 

I think it's worth to add to the docs, or point to PermissionManager install on a new User Model.

**Comment by azaricstefan** [comment]
Yeah, you got it correctly @pxpm, for the users of PermissionManager they would need to have these 2 uses in the upgrade guide.

**Comment by promatik** [comment]
Hi guys 🙌
Just created a PR to fix this lack of information on the upgrade guide.
Lets move the conversation there.

Thank you for your detailed report @azaricstefan 👍
