### ISSUE TITLE
The "try the manual installation process" link returns 404

### ISSUE THREAD

**Issue by kpruhs** [Laravel-Backpack/docs#228]
In the installation.md file in v4.1 the "try the manual installation process" link, at the bottom of the page, returns a 404.
I would recommend a fix but I don't know where the link is supposed to go.  ;-)

**Comment by promatik** [comment]
Hi @kpruhs thank you for submitting the issue.
I've submitted a fix here; #230

In the meanwhile, the correct link is https://backpackforlaravel.com/docs/4.1/crud-how-to#manually-install-backpack
