### ISSUE TITLE
Please document "$this->crud->removeAllButtons();"

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/docs#240]
I discovered only googling the existence of this api.

Google found this: https://github.com/Laravel-Backpack/CRUD/issues/303

I'm looking at: https://backpackforlaravel.com/docs/4.1/crud-api

And do not see "removeAllButtons()"

**Comment by promatik** [comment]
Hi @realtebo thank you for the suggestion.
Indeed those docs where missing, I just added them here; #241
It will soon be merged, thank you for letting us know 👍
