### ISSUE TITLE
Missing doc for 'textarea' column

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/docs#252]
I cannot see here: 

  https://backpackforlaravel.com/docs/4.1/crud-columns

the documentation for `textarea` as column field

Looking at folder `vendor/backpack/crud/src/resources/views/crud/columns` probably are missing also

- custom_html
- json

**Comment by tabacitu** [comment]
Right! Thank you @realtebo , will do!

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/docs/pull/265 - finally closing!
