### ISSUE TITLE
Missing comand elFinder installation

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/docs#259]
The fields [browse](https://backpackforlaravel.com/docs/4.1/crud-fields#browse-1) not work if you don't have elFinder installed. 
This is correct mention in the docs: 

> This button allows the admin to open elFinder and select a file from there. Run `composer require backpack/filemanager` to install elFinder, then you can use the field:

But you need to exectu the install comand to make it work
`php artisan backpack:filemanager:install`

To improve docs add the command in the documentation or link to [FileManager](https://github.com/Laravel-Backpack/FileManager)

**Comment by tabacitu** [comment]
Oups - you're right, of course. Thanks @adriallongarriu . Done in https://github.com/Laravel-Backpack/docs/commit/359a065721b6e36eaf82bac1181515efae20e818
