### ISSUE TITLE
Document how to validate upload_multiple 

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/docs#294]
In https://backpackforlaravel.com/docs/4.1/crud-fields#upload_multiple document that for `upload_multiple`.
Since the form field is an array, the [laravel validation](https://laravel.com/docs/8.x/validation#retrieving-all-error-messages-for-a-field) requires the field name followed by `.*` like so

```php
$request->validate([
    'upload_multiple.*' => [ // field name note the .*
        'file',
        'min:1', 'max:2000', // file size in kiloBytes
        'mimes:jpg',
        'mimetypes:image/jpeg',
    ],
];
```
It can take a long time to figure out why validation is not working if you don't know that.

**Comment by promatik** [comment]
Hi @Polfo!
Thank you for the tip, I agree, this code snipped will improve backpack developers experience 👌
https://github.com/Laravel-Backpack/docs/pull/330 is open to fix this.
