### ISSUE TITLE
[4.1 and 4.2-dev] Screenshot missing?

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/docs#312]
See here: https://backpackforlaravel.com/docs/4.1/crud-filters#simple-1

There is a re to some missing screenshost

> The "Draft" and "Has Video" filters in the screenshot above are simple filters.

**Comment by promatik** [comment]
Hi @realtebo, good catch!
Indeed the image is missing 🙌

https://github.com/Laravel-Backpack/docs/pull/331 is open to fix this.
