### ISSUE TITLE
Duplicate path in upgrade guide

### ISSUE THREAD

**Issue by mattsches** [Laravel-Backpack/docs#326]
`resources/views/vendor/backpack/crud/fields` is mentioned twice in step 20 of the upgrade guide. I'm not quite sure what the fix is.

> do you have anything inside your `resources/views/vendor/backpack/crud/fields` or `resources/views/vendor/backpack/crud/fields`?

https://github.com/Laravel-Backpack/docs/blob/8debebb1cc2fa1be69559b2906f16e9d933ea8b2/5.x/upgrade-guide.md?plain=1#L266

**Comment by promatik** [comment]
Hi @mattsches!

You are totally right, the second reference should be to the `columns` folder.

Thank you for letting us know, and sorry for the trouble, #333 is open to fix that 🙌
