### ISSUE TITLE
Small point: "deduce"

### ISSUE THREAD

**Issue by CharlieNH** [Laravel-Backpack/docs#328]
In writing about relationships (and perhaps elsewhere) you use the verb "deduct" when you mean "deduce." No biggy, obviously, but when you have time to fix it you might want to.

I'm extremely impressed with Backpack. Great software, great documentation ... congratulations to your whole team! 

By the way, I'm curious ... does your online documentation use Jigsaw Docs, or something like it? I really like the look and the functionality, especially the hashmark anchors for each section -- well done!

Thanks,

Charlie

**Comment by promatik** [comment]
Hi @CharlieNH!
Thank you for your suggestion, I learn something new today, the difference between deduce and deduct, it is the same in my language 😅

#332 is open to fix this 🙌

Feel free to open PRs with typo fixes or improvements for backpack documentation, we highly appreciate it since none of backpack maintainers is an English native speaker 😅

**Comment by tabacitu** [comment]
Merged! Thank you @CharlieNH & @promatik  - I also learned something today 😀
We were using it correctly exactly zero times 😅

**Comment by CharlieNH** [comment]
Thanks for your encouragement, guys. I've never done a PR before, but I'd
like to learn.

I am going to be writing some very detailed Backpack tutorials over the
coming year for a book I'm writing. When I've got one that I think is good
enough and useful enough, I'll try to submit it to you as a PR ... I look
forward to learning how to do that.

Keep up the great work with Backpack! The more I learn about it, the more
impressed I am.

Charlie

**Comment by tabacitu** [comment]
OMG that sounds awesome. Reach out if we can help.

Cheers!
