### ISSUE TITLE
CrudFields Javascript API typo

### ISSUE THREAD

**Issue by patricstan** [Laravel-Backpack/docs#356]
### CrudFields Javascript API (10)

```
function calculate_discount_percentage() {
  let full_price = Number(crud.field('full_price').value);
  let discounted_price = Number(crud.field('discounted_price').value);
  let discount_percentage = (full_price - discounted_price) * 100 / full_price;

  crud.field('discount_percentage').input.value = discount_percentage;
}

crud.fields(['full_price', 'discounted_price']).forEach(function(field) {
  field.onChange(calculate_discount_percentage());
});
```

I think there is a typo inside the onChange function, where _calculate_discount_percentage()_ is called. I tried this example and it worked only on page load, but gave an Uncaught TypeError: closure is undefined. From my understanding of closures, references to the instance of the function should be the name of the function without parentheses. So I deleted them and with this code everything went great.
```
crud.fields(['full_price', 'discounted_price']).forEach(function(field) {
  field.onChange(calculate_discount_percentage);
});
```

**Comment by promatik** [comment]
Hi @patricstan!
Thank you for letting us know, you are correct, those `()` should not be there.

I've open https://github.com/Laravel-Backpack/docs/pull/357 to fix that 👌
