### ISSUE TITLE
Uninstall Process does not work if DevTools is installed

### ISSUE THREAD

**Issue by fastdrums** [Laravel-Backpack/docs#366]
I was following the steps here (https://backpackforlaravel.com/docs/5.x/faq#how-do-i-uninstall-backpack-from-my-project) to uninstall backpack from our stats project, but ran into a bunch of composer issues because of having devtools installed.  I think this section needs to be updated to consider the addons and their dependencies during the uninstall process.

**Comment by fastdrums** [comment]
It seems like I cant make DevTools uninstall properly:
"Could not delete /home/vagrant/code/stats.backpackforlaravel.com/vendor/backpack/devtools/.git/objects/pack/pack-7881595c492bfc50b38ed2298f9fee46d80c454a.idx:" is the error i'm getting. I'm not sure if this is something weird with my dev environment, or a larger problem.  

I've been unable to uninstall the other packages because they are required by DevTools:
vagrant@homestead:~/code/stats.backpackforlaravel.com$ composer why backpack/generators
backpack/devtools 1.0.34 requires backpack/generators (^3.1.9)

The only way I was able to get it to uninstall was to do a fresh clone, manually edit the composer.json to not include devtools or the custom repo, and then run composer update to reinstall the site, and then do the 'uninstall backpack' process like normal.  

Perhaps we should add notes about this fix if it ends up being more than an isolated incident?

**Comment by pxpm** [comment]
#375
