### ISSUE TITLE
Revision in versions dropdown

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/docs#381]
The versions are not sorted and the .git show a 404 page

![imagen](https://user-images.githubusercontent.com/20278289/193584165-016f8aaf-8db2-44d2-a3a0-52cef22401aa.png)

**Comment by pxpm** [comment]
Thanks for the report @adriallongarriu :pray: 

ping @tabacitu

**Comment by tabacitu** [comment]
Fixed! Thanks guys 🙏
