### ISSUE TITLE
Widget stacks are not documented in any Operations

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#385]
@jorgetwgroup wanted to add a TOTAL widget to a ListOperation, and it turns out... we haven't documented how to do that. There is absolutely no mention in our operations where the widget stacks are, and how you can take advantage of them.

Let's fix that. Let's:
- add a new section to all operations docs, "how to add widgets", where we 
    - show a screenshot with clear markings, where they are;
    - teach people how to add a widget in one of those places;

**Comment by karandatwani92** [comment]
ok @tabacitu

**Comment by karandatwani92** [comment]
#387
