### ISSUE TITLE
Stop asking me to login, or keep me logged in longer.

### ISSUE THREAD

**Issue by evanrthompson** [Laravel-Backpack/Docs#40]
Figuratively speaking, "every time" I open a browser to review the documentation I'm assaulted with a fullscreen modal encouraging me to login. Which is annoying on the face of it. Worse is that when I do log in the session doesn't seem to stick around very long so when I come back later that day I'm asked to log in again. Makes the documentation very frustrating to pull up.

(Really loving Backpack so far and I'll grant this is a minor issue but it's just driving me 🥜)

**Comment by tabacitu** [comment]
Ouch. I can see why it would be driving you nuts @evanrthompson , sorry for the bad experience. I've been logged in for >1 year and I've never seen the modal. I forgot it even existed. It is NOT our intention to harass you with the modal once logged in. Nor to ever log you out. It must be a bug with our login/session system, or some incompatibility with your browser.

I've been trying to replicate this but I haven't been able to do so in Chrome, Safari, Brave, Firefox or Opera. I just stay logged in - which was our intention.

Q1) What browser are you using?
Q2) Is it possible that you have a very strict session policy in the browser, and the sessions gets deleted more often than usual?
Q3) Are you using a beta/rc/nightly browser distribution, that gets updated every day? Like Chrome Canary?
Q4) How often does the logout happen (aprox)? Do you get logged out multiple times a day? Once a day? Once a week? Once a month?

Glad you're enjoying Backpack - except for this issue :-)
Cheers!

**Comment by evanrthompson** [comment]
1) I'm using Safari - Version 12.1 (14607.1.40.1.4)
2) Not that I'm aware of. Safari is my content browser (as opposed to my dev browser, Chrome) so I don't clear it unless something is messed up under normal circumstances.
3) Nope
4) I'm not forcibly logged out, I'm just not logged in when I return to the site in (what I think is) a reasonable amount of time. This can happen several times a day.

The normal use case for me is to sit down in the morning, open up safari, load up the Backpack docs and login (along with docs sites for other libraries or frameworks involved in my project) and get to work. If I had to guess I'd say the reason is the short expiration on the backpack_session cookie (2 hours) and the fact that it's fairly easy to stay on a single page in the docs without making new requests for much longer than that. Add to that I have a habit of "Clearing the decks" (closing all my open apps and windows)  a few times a day as I move from one project to another and I think all that's happening is that the session is never being renewed while I'm using the docs, and then I reopen/reload the page later that day (sometimes this cycle happens multiple times in a day)

My suggestions here would be to increase the session timeout to a full 24 hours, though if that's not possible for other reasons my second suggestion would be to increase the expiration for the "hide_login_modal" (assuming it does what it says) to one or more days. I don't mind being logged out if there's account or billing information behind that login, the real issue is how frustrating that full-screen login modal / advertisement is when you get halfway into reading a paragraph and it takes over the screen. Given that you can login from the header it seems aggressive.

That one very petty issue aside, I do want to say how impressed I am with Backpack... It's enabled me to get ahead so quickly on this project that I might actually have time to take a vacation soon :)

**Comment by tabacitu** [comment]
Thanks for the details @evanrthompson . Done - 24 hours now. It should be less annoying for people that run into this issue like you.

I still think it's weird though - and it's a niche issue, not a general one. "Remember" is activated when logging you in, and it works for me. I definitely don't refresh the page every 2 hours. Even when not viewing anything for more than 24 hours (ex: over the weekend), I'm still logged in. Again, weird :-)

Hey ho - since it's now 24h it should be less annoying for people. Maybe after I upgrade to Laravel 5.8 it'll fix itself and keep you logged in even longer (like intended). If you do notice you don't get logged out anymore, sometime in the future, please reply here - eager to hear.

Thanks for the kind words about Backpack :-)
Cheers!
