### ISSUE TITLE
Docs for all column types added in v6

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#405]
In v6 we're having a column type for each field type:
- https://github.com/Laravel-Backpack/CRUD/pull/4675
- https://github.com/Laravel-Backpack/PRO/pull/91

That means... we need docs for the new ones.

**Comment by pxpm** [comment]
Hello @karandatwani92 can you please take over this ? 

You can check on https://github.com/Laravel-Backpack/docs/blob/master/6.x/crud-columns.md and https://github.com/Laravel-Backpack/docs/blob/master/6.x/crud-fields.md and create a list of what columns are missing docs.

You can also use the mentioned PR's by @tabacitu as a reference.

Cheers

**Comment by jorgetwgroup** [comment]
hi @tabacitu, column is here: https://github.com/Laravel-Backpack/PRO/pull/125/files was add 3 weeks ago, even you review and ask for some changes.

Cheers.

**Comment by tabacitu** [comment]
Awesome! Then @karandatwani92 we're only missing `google_map` 🎉
