### ISSUE TITLE
404 not found index.md links

### ISSUE THREAD

**Issue by yarscript** [Laravel-Backpack/docs#406]
https://github.com/Laravel-Backpack/docs/blob/master/5.x/index.md
404 index.md links
<img width="832" alt="image" src="https://user-images.githubusercontent.com/26656665/216792770-3c62710c-8a1b-4346-a80a-1d282031ee8c.png">

**Comment by yarscript** [comment]
https://github.com/Laravel-Backpack/docs/pull/407

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/docs/pull/407
