### ISSUE TITLE
Make sure all v6 features are documented

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#450]
To document:
- [x] installation process now asks the developer which theme they want to install;
- [ ] ~~installation process currently favors installing CoreUIv2, so we can't say Tabler is the default just yet;~~
- [x] UPGRADE GUIDE - note all version of our packages that support Backpack v6, so it's easy for people to bump the version;
- [ ] ~~UPGRADE GUIDE - shouldn't we tell people to change all their custom pages to extend `backpack_view('blank')` because that's provided by all themes?~~
- [x] UPGRADE GUIDE: you should run `php artisan backpack:install` to properly install Basset and the theme;
- [x] UPGRADE GUIDE - shouldn't we tell people to delete their `errors` folder? if they haven't customized it with their own error views of course;
- [x] ~~UPGRADE GUIDE - in v6 [we define the uploaders in the `crud.php` config file](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-232890cfa7e10f68dc45f83d557317fecb90332d688417eb7ddd6907ebb51660); do we instruct people to add these in the upgrade guide? what happens if they don't do it?~~ nothing; they will add them when they want to create custom uploaders; which is never;
- [x] ~~UPGRADE GUIDE - in v6 [all operations content class defaults to being wide](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-4d03cc121b578dee76e8a004508dc0d8d826c9c41de8ddfa2443a7e99a8fc653) (`col-md-12`); should we instruct people to do that in their upgrade guide?~~ nah... let's let them keep their old width;
- [x] [CrudButton now has `metas`](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-18b9f32728351bf2b610129d4d9f8e537af03e6e5ab5d964e8efd60427c8121d) and you can send variables to your buttons; is this documented anywhere?
- [x] [CrudColumn is Macroable now](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-822bbd6b54c2a57660512899bb1c23f223d9ae97c9c131d3c7f52cf2bf055193); is that documented anywhere? should we?
- [x] [CrudField is Macroable now](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-56a5891a886237eb59ee663a2dfb15a17a5c130b1e6e705b9d41ef940e7893a5); is that documented anywhere? should we?
- [x] are all Uploaders documented? 
- [x] are all Uploaders referenced where they're most likely to be needed?
- [x] do our general-purpose docs and examples show Uploaders instead of mutators or model events?
- [x] we now have a few [custom validation rules](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-acca32204b1576b3921d62666bbd73696c87b9c542ea6060ea13058c30de89af); are they well documented?
- [x] in v6 we add [a way to quickly add a button](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-80a945cb7f208def321c143b028106692107f70280258d43e7af04ae15d9d01f) - is that properly documented?
- [x] i'm pretty sure the `bp-section` classes we've added aren't documented at all; see [this](https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-b48ae61d38a0e1ed00f1fe3c3d9db30211e72b39f3df890c9beaa87a91a6b1a6) as an example;
- [x] we should document how someone uninstalls a Backpack theme; for ex in the upgrade process we instruct them to use CoreUIv2, and only after everything is workding... install Tabler and uninstall CoreUIv2; but we don't explain how to do that (uninstall);
- [x] currently our docs don't do a good job at highlighting how much of a team effort Backpack v6 was; we MUST give credit where credit is due; we must mention our team members by name; and thank them for their efforts; 
- [x] we should mention how much work has gone into v6, with numbers:
    - CRUD alone has had [more than 614 commits](https://github.com/Laravel-Backpack/CRUD/pull/4860);
    - PRO has had [more than 221 commits](https://github.com/Laravel-Backpack/PRO/pull/123);
- [x] our drip emails for "getting started" have not been updated for v6; at all!
- [x] spatie media library support is nowhere in the docs, only in the release notes;
- [x] https://github.com/Laravel-Backpack/docs/issues/488
- [x] https://github.com/Laravel-Backpack/docs/issues/484

**Comment by tabacitu** [comment]
- [ ] polish all pages that were noted here as not final:

![CleanShot 2023-07-02 at 18 55 30](https://github.com/Laravel-Backpack/docs/assets/1032474/4d1c7d51-803e-4464-95f1-0e9babfd1d43)

**Comment by tabacitu** [comment]
![CleanShot 2023-07-27 at 16 20 59](https://github.com/Laravel-Backpack/docs/assets/1032474/865ef1cc-12cb-49fe-b587-7a1f746a3b8e)

**Comment by pxpm** [comment]
> ![CleanShot 2023-07-27 at 16 20 59](https://user-images.githubusercontent.com/1032474/256584669-865ef1cc-12cb-49fe-b587-7a1f746a3b8e.gif)

I stared at this for a moment thinking you were reporting a bug because the file seems to "disapear" 🤷 funny!
