### ISSUE TITLE
Step 8 in 6.X upgrade guide is incorrect

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/docs#452]
I just upgraded a first app from version 5 to 6 and noticed that the details for Step 8 (https://backpackforlaravel.com/docs/6.x/upgrade-guide#step-8) mention the `ui.php` config file needs to be created. But in my case the `ui.php` config file already existed.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/docs/commit/f90f59611e3d9ff35ceb94945b38776b71cbf640 - thanks @malle-pietje . Now that people do `php artisan backpack:install` before that step, they do indeed have `config/backpack/ui.php` in their projects.
