### ISSUE TITLE
Document what is the purpose of config\backpack\crud.php locales array

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/docs#453]
I am with you since v4 and still don't understand the goal aand the usage of `locales` array in `config\backpack\crud.php `

What changes when enabling or disabling a language?
Why some locales are enable by defaults?

I kindly suggest a small improvment here: https://backpackforlaravel.com/docs/6.x/base-how-to#customize-the-translated-strings-aka-overwrite-the-language-file 

You could add a not to explain that to have the 'starter' app ready for a new language, it's only needed to change the locale in config\app.php because backpack includes all translations

I know this is a laravel feature, but laravel hasn't the translations inside it, so I think it's usefull to evidence that backpack is offering _also_ the default translations. So the paragraph should incorage to 
- change app locale
- overrides NOT THE ENGLISH  but the specific locale when needed

Also, why not point user to where post missing translations and or bug here on github?

**Comment by pxpm** [comment]
Hey @realtebo 

We agree that list is a **huge mess*. We plan to remove it, but it's a breaking change, and we didn't find the opportunity for it to make it into a major release, so I guess we need to leave with that for v6 too 🤷 

That's the list of locales available when using the translatable cruds: https://backpackforlaravel.com/docs/6.x/crud-operation-update#translatable-models

> Change the languages available to translate to/from, in your crud config file (config/backpack/crud.php). By default there are quite a few enabled (English, French, German, Italian, Romanian).


About your other suggestion, i've added: https://github.com/Laravel-Backpack/docs/pull/454 to the docs.

Are we good here, or do you think we can add something more ? 

Cheers
