### ISSUE TITLE
How to use Spatie/Laravel-Media with Backpack

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#46]
Add documentation on how to use upload fields with [spatie/laravel-media](https://github.com/spatie/laravel-medialibrary):
- [ ] section in [CRUD's How To](https://backpackforlaravel.com/docs/3.6/crud-how-to)
- [ ] field type ```browse``` - link to the HowTo section above
- [ ] field type ```browse_multiple``` - link to the HowTo section above
- [ ] field type ```image``` - link to the HowTo section above

**Comment by pmayet** [comment]
Hi @tabacitu ,

Any news about that ?

Thank's !

**Comment by tabacitu** [comment]
Instead of docs, I think we should add a `media` field type. That'll be easiest for most people. And since it's something that many people voted on, that we should do... we're gonna do it. Ideally next month. 

So let's close this in favor of https://github.com/Laravel-Backpack/ideas/issues/28
