### ISSUE TITLE
How to add custom plugins to CKEditor in Backpack v6

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#465]
In https://github.com/Laravel-Backpack/community-forum/issues/559#issuecomment-1630673757 Antonio has outlined the process. Now let's think... where do we document it?
- inside the field? it's too big for that;
- inside the FAQ? too hidden;
- inside a blog post? maybe; but still too hidden;

So how about... we just _mention it_ in the field docs, and link to the issue on Github? That should be a good middle option, right? It's right where people expect it (field docs), it can be as long as possible, and it's already written.

**Comment by karandatwani92** [comment]
PR #472
