### ISSUE TITLE
[Bug] Docs Base > How To page needs updating to reflect the new file/directory structure

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/docs#468]
# Bug report

### What I did

Just going through the installation to check the difference between this theme and the default tabler theme

### What I expected to happen

I expected the file structure to be like it is in the docs!

### What happened

The file/directory structure has changed

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.12-1ubuntu4 (cli) (built: Feb 22 2023 19:48:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12-1ubuntu4, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/generators: v4.0.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.5
backpack/theme-coreuiv4: 1.0.0
backpack/theme-tabler: 1.0.1

Cheers

**Comment by tabacitu** [comment]
Ouch! Indeed that page needs A LOT of love. Thanks @fronbow , on it!

**Comment by tabacitu** [comment]
I've just updated the HowTo page 🎉 In most cases, I've pointed the user to the theme docs. 

Regarding the folder structure, each theme can now have its own folder structure... so we can't really teach anybody about the folder structure in the docs. So we point them to look inside the theme they are using.
