### ISSUE TITLE
Backpack Docs on Dash?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/docs#47]
How can we make Backpack's docs appear in [Dash](https://kapeli.com/dash)?

**Comment by ziming** [comment]
https://github.com/godbout/dash-docset-builder

**Comment by dividy** [comment]
https://kapeli.com/docsets#doxygen

**Comment by tabacitu** [comment]
Sorry guys, I'd like to have this, but unfortunately it wouldn't be a good use of our time, since nobody _actually_ asked for this, and the Backpack online docs have great Algolia search right now.

If anybody's interested in spearheading the effort for, this let me know and we'll reopen. Otherwise the team is busy enough as it is, with maintenance and new features - not enough time to tackle this, which I would say is a "nice-to-have".

Feel free to convince me otherwise though, I might change my mind 😄 
Cheers!
