### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/docs#471]
Page: https://backpackforlaravel.com/docs/6.x/features-free-vs-paid

At the bottom: 

> please [vote on top new features](https://github.com/Laravel-Backpack/CRUD/discussions/3960)

The link is broken

**Comment by tabacitu** [comment]
Unfortunately that got lost when we moved things over to a different repo. We don't have a poll open right now, we'll add a link when we do - https://github.com/Laravel-Backpack/docs/commit/c20274a4d644567ed38c6d44db7ab1174a8337f6
