### ISSUE TITLE
V6 upgrade-guide: step required for filemanager

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/docs#474]
### ERROR
I upgraded my project and found that the URL `admin/elfinder` started throwing **500**.
```
No hint path defined for [backpack]. {"view":{"view":"/home/bulkmake/public_html/resources/views/vendor/elfinder/elfinder.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): No hint path defined for [backpack]. at /home/bulkmake/public_html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112)
```
### I fixed it by republishing the updated views:

Steps required while upgrading:
1) Delete `resources/views/vendor/backpack` folder.
2) Run `php artisan backpack:filemanager:install`

@tabacitu should I submit a PR with the above steps? just asking if you have some short way(one command to republish). Thanks

**Comment by tabacitu** [comment]
Yes please! I think we can instruct people to do:
```
rm -rf resources/views/vendor/elfinder
php artisan backpack:filemanager:install
```

We could/should do this as a LAST step. And make it more general. _For any addons you might have upgraded, please double-check if they have an upgrade guide. For example elFinder needs you to do this xxx_
