### ISSUE TITLE
The "How To" Page got a lot of old info which is not usable in v6

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/docs#488]
We need to update & remove the text instruction and images which are not related to backpack v6 from the "How To" Page such as:
- Change the colors
- Customize the menu or sidebar
- Customizing the design of the menu / sidebar / footer
- Customize the look and feel of the admin panel (using CSS)
- and **many more**

https://backpackforlaravel.com/docs/6.x/base-how-to

**Comment by tabacitu** [comment]
Haha I just pushed a redo of this page yesterday 😉

Thanks Karan!
