### ISSUE TITLE
CRUD Fields address_google API Key

### ISSUE THREAD

**Issue by martyn-johnson** [Laravel-Backpack/docs#517]
Error in the doc https://backpackforlaravel.com/docs/6.x/crud-fields#address_google-pro

Documentation suggests the way to include the Google Places API key is:
'google_places' => [
    'key' => 'the-key-you-got-from-google-places'
],

That does not work, it uses the field 'api_key'.

The correct way to include the Google Places API key is:
'api_key' => 'the-key-you-got-from-google-places',

**Comment by pxpm** [comment]
Hey @martyn-johnson thanks for the report and the heads up. 

Clearly we were not doing a good job, when I looked at the docs I got confused too, so I improved that bit of documentation [in this pull request](https://github.com/Laravel-Backpack/docs/pull/518)

The example is misleading, we were giving the example of what you should use when adding the key in `config/services.php` not in the field definition.

We do not recommend adding the key in the field, I added it as an example in the docs, but mentioned that we do not recommend to do it.

In future we may remove the `$field['api_key']` altogether and leave only the `config/services.php` option. 

Closing this, please re-open, or open a new issue if you found some. 

Cheers 🙏
