### ISSUE TITLE
overwrite register.blade.php instructions are wrong

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/docs#524]
https://backpackforlaravel.com/docs/6.x/base-how-to#add-one-or-more-fields-to-the-register-form-1 has wrong instructions as pointed out in: https://github.com/Laravel-Backpack/community-forum/issues/766#issuecomment-1832550857

I am sure this is a leftover from previous versions, let's fix this please 🙏

**Comment by karandatwani92** [comment]
PR https://github.com/Laravel-Backpack/docs/pull/525

**Comment by pxpm** [comment]
This was done in #525
