### ISSUE TITLE
In upgrade Guide to 4.0 6.1 should come before 6.0

### ISSUE THREAD

**Issue by Patabugen** [Laravel-Backpack/Docs#56]
When upgradingt from 3.6 to 4.0 it's best to do step 6.1 before 6 in the upgrade guide.

This is beacuse 6.1 removes some old parent:: calls which step 6 says you need to change - but you don't actually need to change them (beacuse 6.1 says to remove them).

I can push a pull-request, but I'm not sure about changing the numbering. If you're OK with me making the removal of `public function store(StoreRequest $request)` etc step 6.0 and the removal of `return parent::show();` etc step 6.1 then I'll make a pull request.

**Comment by tabacitu** [comment]
Yup, you're right, of course. I just moved 6.1 to be the last step in 6. So it's now (the previous) 6.2, 6.3, then 6.1. Thanks again!
