### ISSUE TITLE
Discrepancy in step 1 of Getting Started page

### ISSUE THREAD

**Issue by nulele** [Laravel-Backpack/docs#584]
Hello,

I was comparing the `UserCrudController` generated by `php artisan backpack:crud user` command with the step 1 of "Getting Started" page when I first open the admin dashboard and I found a discrepancy.

Well, the documentation says:

1. **When Listing, let's remove the "password" column** - no point in showing the hash. To do that, go to `UserCrudController::setupListOperation()` and remove the line saying `CRUD::column('password');` - easy-peasy, right?

but the method of the controller is:

```
    /**
     * Define what happens when the List operation is loaded.
     * 
     * @see  https://backpackforlaravel.com/docs/crud-operation-list-entries
     * @return void
     */
    protected function setupListOperation()
    {
        CRUD::setFromDb(); // set columns from db columns.

        /**
         * Columns can be defined using the fluent syntax:
         * - CRUD::column('price')->type('number');
         */
    }
```

I have the pro version and the packages versions are:
- backpack/pro: 2.2.4
- backpack/generators: 4.0.5

Maybe do I need to set some configuration parameter?

Thanks

**Comment by jcastroa87** [comment]
Hello @nulele 

Thanks for this, we will check about this docs and updated as needed.

Cheers.

**Comment by jcastroa87** [comment]
Hello @nulele 

Thanks for this found, we are working to fix it now in [this PR](https://github.com/Laravel-Backpack/CRUD/pull/5726)

I will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.
