### ISSUE TITLE
For some examples code formatting is not consistent

### ISSUE THREAD

**Issue by tomsb** [Laravel-Backpack/Docs#65]
Also, in some places there are comments like these and they break "autoformat" like this:
![image](https://user-images.githubusercontent.com/923139/66804061-af0d9780-ef4b-11e9-88bd-1a9a8c3f5a1d.png)

It should behave like this:
![image](https://user-images.githubusercontent.com/923139/66804088-bcc31d00-ef4b-11e9-9324-46ce1c4c1e79.png)

I made some changes to make formatting consistent and moved some comments so that auto format on copy&paste knows how to correctly format the code (tested in PhpStorm)

Pull request: https://github.com/Laravel-Backpack/Docs/pull/66

**Comment by tabacitu** [comment]
True! Thank you for the PR @tomsb !
