### ISSUE TITLE
backpack:add-custom-route and backpack:add-sidebar-content executes twice

### ISSUE THREAD

**Issue by etlekana** [Laravel-Backpack/Docs#68]
This is happening on windows platform.

route add's 2 lines exact the same.
    Route::crud('member', 'MemberCrudController');
    Route::crud('member', 'MemberCrudController');

Sidebar function, make 2 lines, but with bit different.
<li class='nav-item'><a class='nav-link' href='{{ backpack_url('member') }}'><i class='nav-icon fa fa-question'></i> Members</a></li>
<li class='nav-item'><a class='nav-link' href='{{ backpack_url('member') }}'><i class='nav-icon fa fa-user'></i> Members</a></li>

And i am only executing both commands once

**Comment by tabacitu** [comment]
Hi @etlekana ,

I see you've closed the issue - so I assume it's been fixed for you, or maybe user error? Out of curiosity, what was the problem?

Cheers!
