### ISSUE TITLE
backpack:crud is not a command

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [Laravel-Backpack/Docs#77]
I have installed Backpack 4.0.23 and run `php artisan backpack:install`. However, I am having a basic problem following the tutorial.  I have "4.0" selected as my version of Backpack when browsing the documentation. I therefore assume that there is a version of Backpack 4.0.x where `php artisan backpack:crud tag` is a valid command, where x < 23. However, in Backpack 4.0.23, `php artisan backpack:crud tag` fails with the following message: `Command "backpack:crud" is not defined.`

If the command was removed between 3.6 and 4.0.x, it needs to be listed in the Release Notes. Additionally, you need to expand the tutorial to cover the creation of the request file.

**Comment by tabacitu** [comment]
Hi @ssimo3lsuhsc ,

It's possible that you don't have our generators package installed. In our [installation guide](https://backpackforlaravel.com/docs/4.0/installation#install-core-packages), it's a distinct installation command. 

```composer require backpack/generators --dev``` should fix it for you. Let me know if it doesn't.

Cheers!
