### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by onkbear** [Laravel-Backpack/docs#78]
Hi,

Does anyone know which Markdown parser is being used for Docs website?

When I was creating pull request, I found a broken section here.

https://backpackforlaravel.com/docs/4.0/crud-buttons#adding-a-custom-button-with-javascript-to-the-top-stack

It is working on GitHub therefor, I am guessing caused by Markdown parser.

Thanks,

**Comment by tabacitu** [comment]
Ugh. Nasty. Indeed it looks like a parser issue. We're using [erusev/parsedown-extra](https://github.com/erusev/parsedown-extra). But I see they haven't had an update in 2 years...

Do you have a recommendation for a better markdown parser for Laravel? Maybe it's just a matter of swapping out one for the other...

**Comment by onkbear** [comment]
Hi @tabacitu,

Thank you for replying.

I just tried [league/commonmark-extras](https://github.com/thephpleague/commonmark-extras) and it worked for `crud-buttons.md`. I have never used it though...

Another solution is just avoiding the parsing error like:

```diff
 - Create the ```resources\views\vendor\backpack\crud\buttons\import.blade.php``` file:
+
 ```php
 @if ($crud->hasAccess('create'))
```

Which one do you think is better ?

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/docs/pull/112 , thank you @onkbear !
