### ISSUE TITLE
Should be dark mode

### ISSUE THREAD

**Issue by vonsogt** [Laravel-Backpack/Docs#84]
When someone tries to read the document, it kinda feels hurt our eyes when reading all article in white background, so please make the dark mode for Simple & Calm UI

**Comment by tabacitu** [comment]
Thanks @vonsogt ! We'll consider it. We're actually in the process of redesigning backpackforlaravel.com - so it's a very good moment for such a suggestion. We _could_ create the new website in two flavours - light and dark ([depending on the OS setting](https://css-tricks.com/dark-modes-with-css/)). Thanks again, cheers!
